name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Pull Docker image using a dynamically generated tag
      - name: Pull Docker image
        run: docker pull srinivas42/jbpm-full-server-2024:${{ github.run_id }}
        
      # Add any additional steps you need here (for example, building the Docker image, testing, etc.)
