name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: srinivas42/jbpm-full-server-2024
    - name: JBPM
      run: docker pull srinivas42/jbpm-full-server-2024:$(date +%s)
